import { units, lessons, lessonById, unitById } from './curriculum.js';
import { db, state, loadAccount, saveProfile, saveLesson, recordAttempt, saveCalibration, removeCalibration, totals, calibrationForDevice, getDeviceClass, getDeviceId } from './store.js';
import { ASSESSMENTS, calibrationMetrics, visibility } from './assessment.js';
import { startPose } from './pose.js';

const app=document.getElementById('app');
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const route=()=>decodeURIComponent(location.hash.slice(1)||'/home');
const go=path=>{if(route()===path)render();else location.hash='#'+path};
let camera=null, currentRoute='', lessonUI=null, lastCompletion=null, deferredInstall=null, recovering=false;
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstall=event;render()});
window.addEventListener('hashchange',render);
if('serviceWorker' in navigator && location.protocol!=='file:') navigator.serviceWorker.register('./sw.js').catch(()=>{});

function toast(message){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.setAttribute('role','status');el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),5000)}
let cameraRequest=0;
function stopCamera(){cameraRequest++;if(camera){camera.stop();camera=null}}
function brand(){return `<a class="brand" href="#/home" aria-label="RakshaOne home"><img src="./assets/logo.png" alt=""><span class="brand-name">RakshaOne</span></a>`}
const navItems=[['/home','⌂','Home'],['/path','◈','Learn'],['/progress','◉','Progress'],['/achievements','✦','Awards'],['/settings','⚙','Settings']];
function navLink([path,icon,label]){const active=route()===path||path==='/path'&&(route().startsWith('/unit/')||route().startsWith('/lesson/'));return `<a href="#${path}" ${active?'aria-current="page"':''}><span class="icon" aria-hidden="true">${icon}</span><span class="label">${label}</span></a>`}
function shell(content,crumb='Your learning space'){
  const name=state.profile?.display_name||state.user?.email?.split('@')[0]||'Learner';
  return `<div class="app-shell ${route()==='/calibrate'||route().startsWith('/camera/')?'camera-mode':''}"><aside class="sidebar">${brand()}<nav class="nav" aria-label="Main navigation">${navItems.map(navLink).join('')}</nav><div class="sidebar-bottom"><span class="eyebrow">Your north star</span><p class="small" style="margin:6px 0 0">Avoid → de-escalate → create distance → escape → get help.</p></div></aside><main class="main"><div class="content"><div class="topline"><span class="crumb">${escapeHtml(crumb)}</span><a class="user-pill" href="#/settings"><span class="avatar" aria-hidden="true">${escapeHtml(name[0]?.toUpperCase()||'R')}</span>${escapeHtml(name)}</a></div>${content}</div></main><nav class="bottom-nav" aria-label="Mobile navigation">${navItems.map(navLink).join('')}</nav></div>`;
}
function statusText(lessonId){const row=state.progress.get(lessonId);return row?.status==='mastered'?'Mastered':row?.status==='passed'?'Completed':row?.status==='practiced'?'Practiced':row?.status==='learned'?'Learned':row?.status==='viewed'?'Started':'Ready'}
const completed=id=>['passed','mastered'].includes(state.progress.get(id)?.status);
function nextLesson(){return lessons.find(item=>!completed(item.id))||lessons[0]}
function percent(n,d){return d?Math.round(n/d*100):0}
function home(){const t=totals(),next=nextLesson(),unit=unitById.get(next.unitId),daily=state.days.find(x=>x.activity_date===new Date().toLocaleDateString('en-CA'))?.lessons_completed||0,goal=state.profile?.daily_goal||1;
  return shell(`<div class="stack"><section class="hero-card"><div><span class="eyebrow">A little stronger, one choice at a time</span><h1>Good to see you, ${escapeHtml(state.profile.display_name.split(' ')[0])}.</h1><p>Your next step is <strong>${escapeHtml(next.title)}</strong> in ${escapeHtml(unit.title)}. Take a few minutes to practice a choice that can help you reach safety.</p><a class="btn btn-primary" href="#/lesson/${encodeURIComponent(next.id)}">${completed(next.id)?'Review lesson':'Continue learning'} <span aria-hidden="true">→</span></a></div><div class="hero-mark"><img src="./assets/logo.png" alt=""></div></section><div class="grid3"><div class="card stat flat"><strong>${t.streak} day${t.streak===1?'':'s'}</strong><span>Current streak</span></div><div class="card stat flat"><strong>${t.xp} XP</strong><span>Knowledge earned</span></div><div class="card stat flat"><strong>${t.completed}/${lessons.length}</strong><span>Lessons completed</span></div></div><div class="grid2"><section class="card"><div class="row"><div><span class="eyebrow">Today</span><h2 style="margin:6px 0 7px">Your daily goal</h2></div><span class="chip">${daily}/${goal} lesson${goal===1?'':'s'}</span></div><p class="muted small">Steady practice matters more than speed.</p><div class="progress-track" role="progressbar" aria-valuenow="${Math.min(daily,goal)}" aria-valuemin="0" aria-valuemax="${goal}" aria-label="Daily lesson goal"><div class="progress-fill" style="width:${percent(Math.min(daily,goal),goal)}%"></div></div></section><section class="card"><span class="eyebrow">Practice recommendation</span><h2 style="margin:8px 0">Try a calm reset</h2><p class="muted">Look for an exit, take one easy breath, and name one person who could help. A useful drill takes less than a minute.</p><a class="btn btn-soft" href="#/lesson/position.breath">Open mini lesson</a></section></div><section><div class="row"><div><span class="eyebrow">The learning path</span><h2 style="margin:5px 0 0">Your next chapters</h2></div><a class="text-link" href="#/path">View all</a></div><div class="unit-list" style="margin-top:15px">${units.slice(0,3).map(unitCard).join('')}</div></section></div>`,'Home');
}
function unitCard(unit){const n=unit.lessons.filter(item=>completed(item.id)).length;return `<a class="unit-card" href="#/unit/${unit.id}"><span class="unit-icon" aria-hidden="true">${unit.icon}</span><span class="unit-info"><h3>${escapeHtml(unit.title)}</h3><p>${escapeHtml(unit.subtitle)}</p></span><span class="unit-tail"><strong>${n}/${unit.lessons.length}</strong><br><span class="small muted">lessons</span></span></a>`}
function pathPage(){return shell(`<header class="row path-header" style="align-items:end;margin-bottom:24px"><div><span class="eyebrow">Eight chapters · 40 lessons</span><h1 style="margin:7px 0">Learn your way to safety.</h1><p class="muted">Short choices, practical habits, controlled solo movement.</p></div><span class="chip">${totals().completed}/${lessons.length} complete</span></header><div class="unit-list">${units.map(unitCard).join('')}</div>`,'Learning path')}
function unitPage(id){const unit=unitById.get(id);if(!unit)return notFound();const n=unit.lessons.filter(item=>completed(item.id)).length;return shell(`<a class="text-link" href="#/path">← Learning path</a><header style="margin:18px 0 26px"><span class="eyebrow">Unit ${units.indexOf(unit)+1} of ${units.length}</span><h1 style="margin:8px 0">${escapeHtml(unit.title)}</h1><p class="muted">${escapeHtml(unit.subtitle)}</p><div class="progress-track" role="progressbar" aria-valuenow="${n}" aria-valuemin="0" aria-valuemax="${unit.lessons.length}" aria-label="Unit completion"><div class="progress-fill" style="width:${percent(n,unit.lessons.length)}%"></div></div></header><div class="lesson-list">${unit.lessons.map((item,index)=>`<a class="lesson-row ${completed(item.id)?'done':''}" href="#/lesson/${encodeURIComponent(item.id)}"><span class="lesson-no">${completed(item.id)?'✓':index+1}</span><span><h3>${escapeHtml(item.title)}</h3><p>${item.minutes} min · ${item.mode==='partner'?'Partner concept; solo review':item.assessmentId?'Optional camera coaching':'Solo lesson'}</p></span><span class="tail">${statusText(item.id)} →</span></a>`).join('')}</div>`,'Learning path / '+unit.title)}
function lessonPage(id){const item=lessonById.get(id);if(!item)return notFound();if(!lessonUI||lessonUI.id!==id){lessonUI={id,index:0,selected:null,answered:false,correct:false,practiced:false,demoIndex:0};if(!state.progress.has(id))saveLesson(id,'viewed').catch(error=>toast('Progress could not be saved: '+error.message))}const block=item.blocks[lessonUI.index];const body=blockMarkup(block,item);return shell(`<div class="lesson-card"><div class="row" style="margin-bottom:16px"><a class="text-link" href="#/unit/${item.unitId}">← ${escapeHtml(unitById.get(item.unitId).title)}</a><span class="chip">${statusText(id)}</span></div><div class="lesson-head"><span class="eyebrow">Lesson ${item.order+1} · ${item.minutes} min</span><h1 style="margin:8px 0 12px">${escapeHtml(item.title)}</h1><div class="progress-track" role="progressbar" aria-valuenow="${lessonUI.index+1}" aria-valuemin="0" aria-valuemax="${item.blocks.length}" aria-label="Lesson steps"><div class="progress-fill" style="width:${percent(lessonUI.index+1,item.blocks.length)}%"></div></div></div><article class="card"><div class="lesson-block">${body}</div><div class="block-actions"><span class="block-count">${lessonUI.index+1} of ${item.blocks.length}</span><div class="row"><button class="btn btn-quiet" data-action="previous-block" ${lessonUI.index===0?'disabled':''}>Back</button>${block.type==='choice'?`<button class="btn btn-primary" data-action="check-choice" ${lessonUI.selected==null||lessonUI.correct?'disabled':''}>Check answer</button>${lessonUI.correct?`<button class="btn btn-primary" data-action="next-block">Continue →</button>`:''}`:block.type==='practice'?`<button class="btn btn-primary" data-action="practice-done">I practiced safely →</button>`:lessonUI.index===item.blocks.length-1?`<button class="btn btn-primary" data-action="complete-lesson">Finish lesson →</button>`:`<button class="btn btn-primary" data-action="next-block">Continue →</button>`}</div></div></article>${item.assessmentId?`<div class="card flat" style="margin-top:16px"><span class="eyebrow">Optional motion coach</span><h3 style="margin:7px 0">Check your ${escapeHtml(ASSESSMENTS[item.assessmentId].title.toLowerCase())}</h3><p class="muted small">Complete this lesson through the knowledge check. Camera practice can earn mastery after calibration.</p><a class="btn btn-soft" href="#/camera/${id}">Open camera practice →</a></div>`:''}</div>`,'Lesson / '+item.title)}
function blockMarkup(block,item){const e=escapeHtml;if(block.type==='explanation')return `<span class="eyebrow">Understand</span><h2>${e(block.heading)}</h2><p style="font-size:1.2rem">${e(block.text)}</p><p class="muted">${e(block.detail)}</p>`;
  if(block.type==='steps')return `<span class="eyebrow">Make it practical</span><h2>${e(block.heading)}</h2>${item.mode==='movement'?'<p class="privacy">Practice slowly in clear space. Stop if you feel pain or dizziness.</p>':''}${item.mode==='partner'?'<p class="privacy">Any partner drill requires consent, gentle pressure, and supervision. No camera score is offered for partner contact.</p>':''}<ol class="step-list">${block.items.map((step,i)=>`<li><b>${i+1}</b><span>${e(step)}</span></li>`).join('')}</ol>`;
  if(block.type==='demonstration'){const frame=block.frames[lessonUI.demoIndex||0];return `<span class="eyebrow">Manual demonstration</span><h2>${e(block.heading)}</h2><div class="demo-wrap"><div class="demo-art" aria-hidden="true"><div class="demo-person pose-${e(frame.pose)}"><i class="head"></i><i class="torso"></i><i class="arm left"></i><i class="arm right"></i><i class="forearm left"></i><i class="forearm right"></i><i class="leg left"></i><i class="leg right"></i></div><span class="floor-arrow">${frame.pose==='step'?'→':'⌁'}</span></div><div class="demo-copy"><span class="chip">Stage ${(lessonUI.demoIndex||0)+1} of ${block.frames.length}</span><h3>${e(frame.label)}</h3><p>${e(frame.text)}</p><div class="demo-tabs" role="group" aria-label="Demonstration stages">${block.frames.map((stage,i)=>`<button class="demo-tab" data-action="demo-stage" data-index="${i}" aria-pressed="${(lessonUI.demoIndex||0)===i}">${i+1}. ${e(stage.label)}</button>`).join('')}</div></div></div><p class="small muted">This diagram is an approximate front view. Move only within a comfortable range.</p>`}
  if(block.type==='cues')return `<span class="eyebrow">Check your form</span><h2>${e(block.heading)}</h2><div class="cue-grid"><div class="cue-card"><span class="chip good">Helpful cue</span><p>${e(block.do)}</p></div><div class="cue-card"><span class="chip">Watch for</span><p>${e(block.avoid)}</p></div></div>`;
  if(block.type==='visual')return `<span class="eyebrow">See the sequence</span><h2>${e(block.heading)}</h2><div class="visual-route" aria-label="${e(block.labels.join(' then '))}">${block.labels.map((label,i)=>`${i?'<i aria-hidden="true">→</i>':''}<span>${e(label)}</span>`).join('')}</div><p class="muted">Notice the path before you need it. A clear route matters more than a perfect move.</p>`;
  if(block.type==='practice')return `<span class="eyebrow">Try it</span><h2>${e(block.heading)}</h2><div class="practice-panel"><p>${e(block.text)}</p></div><p class="muted small" style="margin-top:18px">Take your time. Do only what feels safe and comfortable.</p>`;
  if(block.type==='choice')return `<span class="eyebrow">Quick decision</span><h2>${e(block.prompt)}</h2><div class="choice-list" role="group" aria-label="Choose one answer">${block.options.map((option,i)=>`<button class="choice-option ${lessonUI.selected===i?'selected':''} ${lessonUI.answered&&lessonUI.selected===i?(lessonUI.correct?'correct':'wrong'):''}" data-action="select-choice" data-index="${i}" ${lessonUI.correct?'disabled':''}>${e(option)}</button>`).join('')}</div>${lessonUI.answered?`<div class="feedback ${lessonUI.correct?'':'error'}" role="status"><strong>${lessonUI.correct?'Good decision.':'Try another option.'}</strong><br>${e(block.why)}</div>`:''}`;
  return `<span class="eyebrow">Remember</span><h2>${e(block.heading)}</h2><p style="font-size:1.2rem">${e(block.text)}</p><div class="privacy">The goal is to reduce risk and reach help. No technique guarantees safety.</div>`;
}
function completionPage(id){const item=lessonById.get(id);if(!item)return notFound();const next=lessons[lessons.indexOf(item)+1];return shell(`<section class="card" style="max-width:680px;margin:30px auto;text-align:center;padding:42px"><span style="font-size:3.5rem" aria-hidden="true">✦</span><span class="eyebrow" style="display:block;margin:13px">Lesson complete</span><h1>${escapeHtml(item.title)}</h1><p class="muted">You practiced a choice that can help you reach safety. Keep the habit gentle and repeatable.</p><div class="chip good">${lastCompletion?.id===id&&lastCompletion.xp?`+${lastCompletion.xp} XP earned`:'Progress saved'}</div><div style="display:flex;justify-content:center;gap:9px;flex-wrap:wrap;margin-top:28px">${item.assessmentId?`<a class="btn btn-soft" href="#/camera/${id}">Try camera coaching</a>`:''}${next?`<a class="btn btn-primary" href="#/lesson/${next.id}">Next lesson →</a>`:`<a class="btn btn-primary" href="#/path">Review the path →</a>`}</div></section>`,'Lesson complete')}
function progressPage(){const t=totals();return shell(`<header><span class="eyebrow">Progress that means something</span><h1 style="margin:7px 0">Your learning, at a glance.</h1><p class="muted">Completion follows a correct decision. Camera mastery adds a controlled movement assessment where appropriate.</p></header><div class="grid3" style="margin:24px 0"><div class="card stat"><strong>${t.completed}</strong><span>Lessons passed</span></div><div class="card stat"><strong>${t.mastered}</strong><span>Camera skills mastered</span></div><div class="card stat"><strong>${t.streak}</strong><span>Day streak</span></div></div><div class="card"><div class="row"><h2>Units</h2><span class="chip">Level ${t.level} · ${t.xp} XP</span></div><div class="stack">${units.map(unit=>{const n=unit.lessons.filter(x=>completed(x.id)).length;return `<a href="#/unit/${unit.id}"><div class="row" style="margin-bottom:8px"><strong>${escapeHtml(unit.title)}</strong><span class="small muted">${n}/${unit.lessons.length}</span></div><div class="progress-track"><div class="progress-fill" style="width:${percent(n,unit.lessons.length)}%"></div></div></a>`}).join('')}</div></div><div class="card flat" style="margin-top:18px"><h3>What the labels mean</h3><p class="muted small"><strong>Started</strong> means opened. <strong>Practiced</strong> means a guided drill was done. <strong>Completed</strong> means the decision check was passed. <strong>Mastered</strong> means a supported solo camera exercise also met its assessment criteria.</p></div>`,'Progress')}
const badges=[['First safe choice','Complete your first lesson',t=>t.completed>=1,'✦'],['Five steady steps','Complete five lessons',t=>t.completed>=5,'◈'],['Consistent learner','Practice on three consecutive days',t=>t.streak>=3,'◉'],['Camera explorer','Master one supported solo skill',t=>t.mastered>=1,'◇'],['Halfway there','Complete 20 lessons',t=>t.completed>=20,'↗'],['All eight chapters','Complete every lesson',t=>t.completed===lessons.length,'✺']];
function achievementsPage(){const t=totals();return shell(`<header><span class="eyebrow">Little milestones</span><h1 style="margin:7px 0">Earned through learning.</h1><p class="muted">These celebrate steady progress and good choices, never risky speed.</p></header><div class="badge-grid" style="margin-top:23px">${badges.map(([name,desc,has,symbol])=>`<div class="badge ${has(t)?'':'locked'}"><div class="symbol" aria-hidden="true">${symbol}</div><h3>${name}</h3><p class="small muted">${desc}</p><span class="chip ${has(t)?'good':''}">${has(t)?'Earned':'Keep learning'}</span></div>`).join('')}</div>`,'Awards')}
function settingsPage(){const p=state.profile;const cal=calibrationForDevice();return shell(`<header><span class="eyebrow">Your space</span><h1 style="margin:7px 0">Settings</h1><p class="muted">Choose a manageable pace and keep camera setup specific to this device.</p></header><div class="grid2" style="margin-top:24px"><section class="card"><h2>Profile</h2><form id="settings-form" class="form"><div class="field"><label for="display-name">Name</label><input id="display-name" name="name" maxlength="60" required value="${escapeHtml(p.display_name)}"></div><div class="field"><label for="daily-goal">Daily lesson goal</label><select id="daily-goal" name="goal">${[1,2,3,4,5].map(x=>`<option value="${x}" ${p.daily_goal===x?'selected':''}>${x} lesson${x===1?'':'s'}</option>`).join('')}</select></div><button class="btn btn-primary" type="submit">Save changes</button></form><p class="small muted" style="margin-top:22px">Signed in as ${escapeHtml(state.user.email)}</p><button class="btn btn-quiet" data-action="signout">Sign out</button></section><section class="card"><h2>Camera & privacy</h2><p class="muted small">Current device: <strong>${getDeviceClass()}</strong>. ${cal?`Calibrated · quality ${cal.quality}/100`:'No calibration saved yet.'}</p><p class="privacy">Video stays in your browser. RakshaOne stores derived body proportions and assessment scores, never camera footage.</p><div class="camera-controls"><a class="btn btn-soft" href="#/calibrate">${cal?'Recalibrate':'Calibrate camera'}</a>${cal?'<button class="btn btn-danger" data-action="delete-calibration">Delete calibration</button>':''}</div><hr style="border:0;border-top:1px solid var(--line);margin:24px 0"><h3>Install RakshaOne</h3><p class="small muted">Add the app to your home screen for a focused, app-like experience.</p>${deferredInstall?'<button class="btn btn-quiet" data-action="install">Install app</button>':'<p class="small muted">Use your browser’s “Add to Home Screen” or install menu if available.</p>'}</section></div>`,'Settings')}
function notFound(){return shell(`<section class="card"><h1>That page is not here.</h1><p>Return to the learning path and choose a lesson.</p><a class="btn btn-primary" href="#/path">Open learning path</a></section>`,'Page not found')}

function authPage(mode){const signup=mode==='signup',reset=mode==='reset';return `<div class="auth-wrap"><section class="auth-story">${brand()}<span class="eyebrow">Practical safety, one step at a time</span><h1>Learn to notice. Choose. Move. Get help.</h1><p>RakshaOne gives you short lessons, realistic decisions, and private movement coaching to build safer habits.</p><div class="auth-points"><div><b>01</b> Calm, useful learning for everyday situations</div><div><b>02</b> Solo-first practice and clear safety guidance</div><div><b>03</b> Camera analysis stays on your device</div></div></section><section class="auth-panel"><div class="auth-box"><span class="eyebrow">${reset?'Account help':signup?'Start learning':'Welcome back'}</span><h2>${reset?'Reset your password':signup?'Create your account':'Sign in to continue'}</h2><p class="muted">${reset?'We will email you a reset link.':signup?'A safer choice starts here.':'Pick up exactly where you left off.'}</p><form id="auth-form" data-mode="${mode}" class="form"><div class="field"><label for="auth-email">Email</label><input id="auth-email" name="email" type="email" autocomplete="email" required placeholder="you@example.com"></div>${reset?'':`<div class="field"><label for="auth-password">Password</label><input id="auth-password" name="password" type="password" autocomplete="${signup?'new-password':'current-password'}" minlength="8" required placeholder="At least 8 characters"></div>`}<p id="auth-message" role="status" style="display:none"></p><button type="submit" class="btn btn-primary">${reset?'Send reset link':signup?'Create account':'Sign in'}</button></form><div style="margin-top:22px">${reset?'<a class="text-link" href="#/signin">Back to sign in</a>':signup?'Already have an account? <a class="text-link" href="#/signin">Sign in</a>':'New here? <a class="text-link" href="#/signup">Create an account</a><br><a class="text-link" href="#/reset">Forgot password?</a>'}</div><p class="small muted" style="margin-top:35px">Personal safety skills reduce risk; no technique guarantees protection.</p></div></section></div>`}
function onboardingPage(){return shell(`<section class="card" style="max-width:680px;margin:35px auto;padding:36px"><span class="eyebrow">One quick introduction</span><h1>Let's make this yours.</h1><p class="muted">A name and a small daily goal are enough to begin. Camera setup can wait until your first movement lesson.</p><form id="onboarding-form" class="form"><div class="field"><label for="onboard-name">What should we call you?</label><input id="onboard-name" name="name" maxlength="60" required placeholder="Your first name" value="${escapeHtml(state.user?.user_metadata?.name||'')}"></div><div class="field"><label for="onboard-goal">A comfortable daily goal</label><select id="onboard-goal" name="goal"><option value="1">1 lesson a day</option><option value="2">2 lessons a day</option><option value="3">3 lessons a day</option></select></div><div class="privacy">Our approach: avoid → de-escalate → create distance → escape → get help. Physical practice is optional and should feel controlled.</div><button type="submit" class="btn btn-primary">Begin learning →</button></form></section>`,'Getting started')}
function newPasswordPage(){return shell(`<section class="card" style="max-width:580px;margin:35px auto"><span class="eyebrow">Account recovery</span><h1>Choose a new password.</h1><p class="muted">Use at least eight characters. Your learning progress will stay with your account.</p><form id="new-password-form" class="form"><div class="field"><label for="new-password">New password</label><input id="new-password" name="password" type="password" autocomplete="new-password" minlength="8" required></div><button class="btn btn-primary" type="submit">Update password</button></form></section>`,'Password reset')}
function cameraFrame(){return `<div class="camera-stage"><video id="pose-video" autoplay muted playsinline aria-label="Live camera preview"></video><canvas id="pose-canvas" aria-label="Live pose and target alignment overlay"></canvas><div class="camera-placeholder" id="camera-placeholder"><div><img src="./assets/logo.png" alt=""><p>Camera starts only when you choose.</p></div></div><div class="camera-overlay"><span id="camera-live-status">Camera off</span><span>Local pose analysis</span></div></div>`}
function calibrationPage(){const cal=calibrationForDevice();return shell(`<a class="text-link" href="#/settings">← Settings</a><header style="margin:15px 0 24px"><span class="eyebrow">Device-specific setup</span><h1 style="margin:7px 0">Calibrate your camera.</h1><p class="muted">Place your phone or webcam far enough away to show your full body. Good light and a clear floor help tracking.</p></header><div class="camera-layout"><div>${cameraFrame()}<div class="camera-controls"><button class="btn btn-primary" data-action="start-calibration">Start camera</button><button class="btn btn-quiet" data-action="switch-camera">Switch camera</button><button class="btn btn-quiet" data-action="stop-camera">Stop</button></div><p class="privacy" style="margin-top:18px">Camera frames are processed here in your browser. Only body proportions and a quality score are saved to your account.</p></div><aside class="card"><span class="eyebrow">Two simple positions</span><h2 style="margin:8px 0">${cal?'Refresh your setup':'Find your frame'}</h2><ol class="step-list"><li><b>1</b><span>Stand naturally with your whole body inside the dashed guide. Keep arms relaxed.</span></li><li><b>2</b><span>Raise both arms gently out to the sides, if comfortable, and hold still briefly.</span></li></ol><p id="camera-message" role="status" class="muted small">Start the camera to begin.</p><div id="calibration-actions" class="stack"><button class="btn btn-soft" data-action="capture-neutral" disabled>Save neutral stance</button><button class="btn btn-soft" data-action="capture-arms" disabled>Save arms-out reference</button></div><p class="small muted" style="margin-top:18px">Current device: ${getDeviceClass()} · ${cal?'Existing setup quality '+cal.quality+'/100':'No saved setup'}</p></aside></div>`,'Camera calibration')}
function cameraPage(id){const item=lessonById.get(id);if(!item?.assessmentId)return notFound();const config=ASSESSMENTS[item.assessmentId],cal=calibrationForDevice();if(!cal)return shell(`<section class="card" style="max-width:700px;margin:35px auto"><span class="eyebrow">One-time setup on this device</span><h1>Calibrate before coaching.</h1><p class="muted">Your ${getDeviceClass()} camera needs its own body and framing reference. This avoids applying a setup from another device.</p><a class="btn btn-primary" href="#/calibrate">Calibrate this camera →</a><a class="btn btn-quiet" style="margin-left:8px" href="#/lesson/${id}">Back to lesson</a></section>`,'Camera setup');return shell(`<a class="text-link" href="#/lesson/${id}">← ${escapeHtml(item.title)}</a><header style="margin:15px 0 24px"><span class="eyebrow">Private motion coach · ${config.kind==='dynamic'?'Movement sequence':'Steady position'}</span><h1 style="margin:7px 0">${escapeHtml(config.title)}</h1><p class="muted">${escapeHtml(config.view)} ${escapeHtml(config.target)}</p></header><div class="camera-layout"><div>${cameraFrame()}<div class="camera-controls"><button class="btn btn-primary" data-action="start-assessment">Start practice</button><button class="btn btn-quiet" data-action="switch-camera">Switch camera</button><button class="btn btn-quiet" data-action="stop-camera">Stop</button><a class="btn btn-quiet" href="#/calibrate">Recalibrate</a></div><p class="privacy" style="margin-top:18px">Your video never leaves this device. We save only the derived score, criterion results, and your calibration proportions.</p></div><aside class="card"><span class="eyebrow">Live guidance</span><h2 style="margin:7px 0" id="score-heading">Get into position</h2><p id="camera-message" role="status" class="muted small">Start practice, then keep your body in the guide.</p><div class="chip" id="phase-chip">${config.kind==='dynamic'?'Phase: ready':'Steady position'}</div><div id="criteria-list" style="margin:17px 0"><p class="muted small">Your criteria will appear when tracking begins.</p></div><div class="feedback" id="correction-box" aria-live="polite">A dashed figure shows approximate target alignment. Green means good, amber means adjust, coral means needs work.</div><button class="btn btn-primary" data-action="finish-assessment" id="finish-assessment" disabled>Complete assessment</button><p class="small muted" style="margin-top:14px">A score reflects visible body position only; it cannot predict real-world safety.</p></aside></div>`,'Camera practice')}
function assessmentResultPage(id){const item=lessonById.get(id);const saved=state.attempts.find(a=>a.lesson_id===id&&a.kind==='camera');const result=lastCompletion?.id===id&&lastCompletion.assessment?lastCompletion.assessment:saved?{score:saved.score,criteria:ASSESSMENTS[item?.assessmentId]?.criteria.map(rule=>({label:rule.label,score:saved.criteria?.scores?.[rule.id]??0,status:(saved.criteria?.scores?.[rule.id]??0)>=80?'good':'needs work'}))||[],corrections:saved.criteria?.corrections||[]}:null;if(!item||!result)return shell(`<section class="card"><h1>No recent assessment.</h1><a class="btn btn-primary" href="#/lesson/${id}">Return to lesson</a></section>`,'Assessment');return shell(`<div class="grid2"><section class="card"><span class="eyebrow">Assessment complete</span><h1 style="margin:8px 0">${escapeHtml(item.title)}</h1><div class="result-score">${result.score}</div><h2>${result.score>=80?'Strong attempt':'Keep practicing gently'}</h2><p class="muted">${result.score>=80?'You met the visible movement criteria. Keep your focus on safe decisions and control.':'Review one correction at a time. The lesson remains complete even if camera tracking is difficult.'}${!completed(id)?' Complete the lesson decision check to earn mastery.':''}</p><a class="btn btn-primary" href="#/lesson/${id}">Back to lesson</a><a class="btn btn-soft" href="#/camera/${id}">Try again</a></section><section class="card"><h2>What the camera saw</h2>${result.criteria.map(c=>`<div class="criterion"><strong>${escapeHtml(c.label)}</strong><span>${c.score}/100 · ${escapeHtml(c.status)}</span><div class="mini-track"><i style="width:${c.score}%"></i></div></div>`).join('')}<div class="feedback" style="margin-top:18px"><strong>Next cue</strong><br>${escapeHtml(result.corrections[0]||'Keep a relaxed, balanced position.')}</div></section></div>`,'Assessment result')}

async function render(){const path=route();if(currentRoute!==path){stopCamera();currentRoute=path;window.scrollTo({top:0,behavior:'instant'})}if(state.loading){app.innerHTML='<div class="boot"><img src="./assets/logo.png" alt="RakshaOne"><p>Preparing your learning space…</p></div>';return}
  if(!state.user){app.innerHTML=authPage(path==='/signup'?'signup':path==='/reset'?'reset':'signin');return}
  if(path==='/new-password'){app.innerHTML=newPasswordPage();return}
  if(!state.profile?.onboarding_complete){app.innerHTML=onboardingPage();return}
  const parts=path.split('/').filter(Boolean);
  app.innerHTML=path==='/home'?home():path==='/path'?pathPage():parts[0]==='unit'?unitPage(parts[1]):parts[0]==='lesson'?lessonPage(parts[1]):parts[0]==='complete'?completionPage(parts[1]):parts[0]==='camera'?cameraPage(parts[1]):parts[0]==='assessment'?assessmentResultPage(parts[1]):path==='/progress'?progressPage():path==='/achievements'?achievementsPage():path==='/settings'?settingsPage():path==='/calibrate'?calibrationPage():notFound();
}

document.addEventListener('submit',async event=>{
  const form=event.target;if(!['auth-form','onboarding-form','settings-form','new-password-form'].includes(form.id))return;
  event.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;
  try{
    if(form.id==='auth-form'){
      const email=form.elements.namedItem('email').value.trim(),mode=form.dataset.mode;
      const password=form.elements.namedItem('password')?.value;
      const response=mode==='signup'?await db.auth.signUp({email,password}):mode==='reset'?await db.auth.resetPasswordForEmail(email,{redirectTo:location.href.split('#')[0]}):await db.auth.signInWithPassword({email,password});
      if(response.error)throw response.error;
      if(mode==='reset'||mode==='signup'&&!response.data?.session){const msg=document.getElementById('auth-message');msg.className='success-line';msg.textContent=mode==='reset'?'Check your email for a password reset link.':'Account created. If confirmation is enabled on this project, check your email to continue.';msg.style.display='block'}
      else{await loadAccount();go('/home')}
    }else if(form.id==='new-password-form'){const {error}=await db.auth.updateUser({password:form.elements.namedItem('password').value});if(error)throw error;recovering=false;toast('Password updated.');go('/settings')}
    else if(form.id==='onboarding-form'){await saveProfile({display_name:form.elements.namedItem('name').value.trim(),daily_goal:Number(form.elements.namedItem('goal').value),onboarding_complete:true});go('/home')}
    else{await saveProfile({display_name:form.elements.namedItem('name').value.trim(),daily_goal:Number(form.elements.namedItem('goal').value),onboarding_complete:true});toast('Settings saved.');render()}
  }catch(error){const msg=document.getElementById('auth-message');if(msg){msg.className='error-line';msg.textContent=error.message;msg.style.display='block'}else toast('Could not save: '+error.message)}finally{button.disabled=false}
});

document.addEventListener('click',async event=>{
  const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;
  try{
    if(action==='select-choice'){lessonUI.selected=Number(button.dataset.index);lessonUI.answered=false;render();return}
    if(action==='demo-stage'){lessonUI.demoIndex=Number(button.dataset.index);render();return}
    if(action==='previous-block'){lessonUI.index=Math.max(0,lessonUI.index-1);lessonUI.selected=null;lessonUI.answered=false;lessonUI.correct=false;render();return}
    if(action==='next-block'){lessonUI.index++;lessonUI.selected=null;lessonUI.answered=false;lessonUI.correct=false;render();return}
    if(action==='check-choice'){const item=lessonById.get(lessonUI.id),block=item.blocks[lessonUI.index];lessonUI.answered=true;lessonUI.correct=lessonUI.selected===block.answer;await recordAttempt(item.id,item.id+'.'+block.id,'quiz',lessonUI.correct?100:0,lessonUI.correct,{selected:lessonUI.selected});render();return}
    if(action==='practice-done'){const item=lessonById.get(lessonUI.id);await recordAttempt(item.id,item.id+'.practice','guided',null,true);await saveLesson(item.id,'practiced');lessonUI.index++;render();return}
    if(action==='complete-lesson'){const item=lessonById.get(lessonUI.id);const cameraPass=state.attempts.some(a=>a.lesson_id===item.id&&a.kind==='camera'&&a.passed&&a.score>=80);const outcome=await saveLesson(item.id,cameraPass?'mastered':'passed');lastCompletion={id:item.id,xp:outcome.xp};go('/complete/'+item.id);return}
    if(action==='signout'){stopCamera();const {error}=await db.auth.signOut();if(error)throw error;state.user=null;state.profile=null;state.progress.clear();go('/signin');return}
    if(action==='delete-calibration'){await removeCalibration(getDeviceId());toast('Calibration deleted from this device profile.');render();return}
    if(action==='install'&&deferredInstall){await deferredInstall.prompt();deferredInstall=null;render();return}
    if(action==='stop-camera'){stopCamera();cameraStatus('Camera stopped.');return}
    if(action==='switch-camera'){const next=window.__facing==='environment'?'user':'environment';window.__facing=next;const calibration=route()==='/calibrate';await beginCamera(calibration,next);return}
    if(action==='start-calibration')return beginCamera(true,window.__facing||'user');
    if(action==='start-assessment')return beginCamera(false,window.__facing||'user');
    if(action==='capture-neutral')return captureCalibration('neutral');
    if(action==='capture-arms')return captureCalibration('arms');
    if(action==='finish-assessment')return finishAssessment();
  }catch(error){toast(error.message||'Something went wrong. Please try again.')}
});

function cameraStatus(message){const el=document.getElementById('camera-message');if(el)el.textContent=message;const badge=document.getElementById('camera-live-status');if(badge)badge.textContent=message.length>45?message.slice(0,42)+'…':message}
let frame=null, neutralPose=null, face=null, stableSince=0, bestResult=null, lastUiUpdate=0;
async function beginCamera(calibration,facingMode){stopCamera();const requestId=++cameraRequest;frame=null;neutralPose=null;stableSince=0;bestResult=null;const id=route().split('/')[2],item=lessonById.get(id);const assessmentId=calibration?null:item?.assessmentId;const video=document.getElementById('pose-video'),canvas=document.getElementById('pose-canvas');if(!video||!canvas)return;cameraStatus('Requesting camera…');try{
    const started=await startPose({video,canvas,assessmentId,calibration:calibration?null:calibrationForDevice()?.metrics,facingMode,onStatus:cameraStatus,onFrame:data=>{
      if(requestId!==cameraRequest)return;frame=data;document.getElementById('camera-placeholder')?.remove();
      if(calibration){const valid=data.visibility.ok;const neutralButton=document.querySelector('[data-action=capture-neutral]');const armsButton=document.querySelector('[data-action=capture-arms]');if(neutralButton)neutralButton.disabled=!valid;if(armsButton)armsButton.disabled=!valid||!neutralPose;if(performance.now()-lastUiUpdate>400){cameraStatus(valid?neutralPose?'Now raise your arms out gently, then save the reference.':'Stand naturally, then save your neutral stance.':data.visibility.message);lastUiUpdate=performance.now()}return}
      const result=data.result;if(!result)return;
      if(result.valid&&result.score>=80&&(assessmentId&&ASSESSMENTS[assessmentId].kind==='static'||data.session.phase==='settle')){
        if(!stableSince)stableSince=performance.now();if(performance.now()-stableSince>1600){bestResult=result;const finish=document.getElementById('finish-assessment');if(finish)finish.disabled=false}
      }else stableSince=0;
      if(performance.now()-lastUiUpdate<250)return;lastUiUpdate=performance.now();
      cameraStatus(result.valid?`${result.quality}% visibility · ${result.message}`:result.message);
      const heading=document.getElementById('score-heading');if(heading)heading.textContent=result.valid?`${result.score} · ${result.score>=80?'Strong attempt':'Keep adjusting'}`:'Improve framing';
      const phase=document.getElementById('phase-chip');if(phase&&assessmentId&&ASSESSMENTS[assessmentId].kind==='dynamic')phase.textContent='Phase: '+data.session.phase;
      const list=document.getElementById('criteria-list');if(list)list.innerHTML=result.valid?result.criteria.map(c=>`<div class="criterion"><strong>${escapeHtml(c.label)}</strong><span>${c.score}/100 · ${escapeHtml(c.status)}</span><div class="mini-track"><i style="width:${c.score}%"></i></div></div>`).join(''):'<p class="muted small">Move until all key joints are visible.</p>';
      const correction=document.getElementById('correction-box');if(correction)correction.textContent=result.valid?(result.corrections.length?result.corrections.join(' '):'Good visible alignment. Keep breathing and stay balanced.'):'Tracking needs a clearer full-body view.';
    }});
    if(requestId!==cameraRequest)started.stop();else camera=started;
  }catch(error){if(requestId===cameraRequest){cameraStatus(`Camera unavailable: ${error.message} You can still complete the lesson knowledge check.`);toast('Camera could not start. Check permission, HTTPS, and connection.')}}}
async function captureCalibration(stage){if(!frame?.visibility.ok||!frame.pose){toast('Please show your whole body in the guide first.');return}if(stage==='neutral'){neutralPose=frame.pose.map(p=>({...p}));cameraStatus('Neutral stance saved. Raise both arms out comfortably.');return}if(!neutralPose)return;const arms=frame.pose;const armSeen=visibility(arms,'open_guard');if(!armSeen.ok){toast('Keep both wrists visible while your arms are out.');return}const quality=Math.min(visibility(neutralPose).quality,armSeen.quality);const armOpen=Math.abs(arms[15].x-arms[16].x)>Math.abs(neutralPose[11].x-neutralPose[12].x)*1.8;if(!armOpen){toast('Move your arms farther out to the sides, then try again.');return}const metrics=calibrationMetrics(neutralPose,arms,frame.video.videoWidth,frame.video.videoHeight);if(metrics.bodyHeight<0.3||metrics.shoulderWidth<0.04){toast('Move closer or adjust the camera so your body is clear.');return}await saveCalibration(getDeviceId(),getDeviceClass(),metrics,quality);stopCamera();toast('Calibration saved for this device.');go('/settings')}
async function finishAssessment(){const id=route().split('/')[2],item=lessonById.get(id);if(!item||!bestResult)return;const result=bestResult;stopCamera();await recordAttempt(item.id,item.id+'.'+item.assessmentId,'camera',result.score,true,{scores:Object.fromEntries(result.criteria.map(c=>[c.id,c.score])),corrections:result.corrections,quality:result.quality});await saveLesson(item.id,completed(id)?'mastered':'practiced',result.score);lastCompletion={id,assessment:result};go('/assessment/'+id)}

db.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){stopCamera();recovering=false;state.user=null;state.profile=null;state.progress.clear();render()}if(event==='PASSWORD_RECOVERY'){recovering=true;setTimeout(()=>loadAccount().then(()=>go('/new-password')).catch(error=>toast(error.message)),0)}});
loadAccount().then(()=>{if(!location.hash)location.hash='#/home';render()}).catch(error=>{state.loading=false;app.innerHTML=authPage('signin');toast('Could not load account: '+error.message)});
