// Curriculum v1. IDs are permanent; order is only presentation metadata.
export const CONTENT_VERSION = 1;
const choice = (prompt, options, answer, why) => ({ id: 'check', type: 'choice', prompt, options, answer, why });
const lesson = (id, title, summary, steps, check, extra = {}) => ({
  id, title, summary, minutes: extra.minutes || 5, mode: extra.mode || 'solo',
  blocks: [
    { id: 'idea', type: 'explanation', heading: 'The idea', text: summary, detail: extra.detail || (extra.mode === 'movement' ? 'Practice slowly in clear space. The purpose of this movement is to make room to leave, not to stay in a confrontation.' : extra.mode === 'partner' ? 'A release may fail in a real situation. Use any opening to get away and seek help.' : 'Notice the situation early. Choose the safest available exit and ask for help when you need it.') },
    ...(extra.demo ? [{ id: 'show', type: 'demonstration', heading: 'See the movement', frames: extra.demo }] : []),
    { id: 'method', type: 'steps', heading: extra.mode === 'movement' ? 'Move with control' : 'Try this', items: steps },
    ...(extra.cues ? [{ id: 'cues', type: 'cues', heading: 'Cues and common mistakes', ...extra.cues }] : []),
    ...(extra.diagram ? [{ id: 'map', type: 'visual', heading: extra.diagram.heading, labels: extra.diagram.labels }] : []),
    { id: 'practice', type: 'practice', heading: 'One-minute practice', text: extra.practice || 'Imagine a familiar place. Name an exit, a safer place, and someone you could ask for help.' },
    check,
    { id: 'recap', type: 'recap', heading: 'Take with you', text: extra.recap || steps[0] }
  ],
  assessmentId: extra.assessmentId || null
});
const C = choice;
export const units = [
  { id: 'foundations', title: 'Safety starts before trouble', subtitle: 'Build a calm, practical safety mindset.', icon: '◈', lessons: [
    lesson('foundations.priority', 'The five-step safety ladder', 'Avoid → de-escalate → create distance → escape → get help. The goal is reaching safety, never winning a confrontation.', ['Look for a way to leave before engaging.', 'Use a calm voice only if it helps you leave.', 'Move toward people, light, and a safe exit; call for help.'], C('Someone blocks a conversation and raises their voice. What is your first aim?', ['Prove you are right', 'Find a safe route away', 'Move closer so they hear you'], 1, 'Leaving lowers exposure. An argument can wait until you are safe.'), {practice:'Look around your current room. Point to two exits and name a person you could contact.'}),
    lesson('foundations.support', 'Your help network', 'A useful safety plan includes trusted people, public places, and local emergency help.', ['Name two trusted adults or contacts.', 'Know where you could seek staffed help nearby.', 'Keep emergency calling available on your phone.'], C('You feel unsafe outside a shop. Which choice gives the best immediate support?', ['Stay isolated and wait', 'Enter the staffed shop and ask for help', 'Post online and keep walking'], 1, 'A staffed public place gives immediate help and witnesses.'), {practice:'Save or review a trusted contact and your local emergency number. Do not call as a drill.'}),
    lesson('foundations.instinct', 'Notice discomfort early', 'A feeling that something is off is enough reason to choose a safer option. You do not owe a stranger an explanation.', ['Pause and name what changed.', 'Increase distance without debating your feeling.', 'Tell a trusted person if concern persists.'], C('A stranger asks you to follow them somewhere private. You feel uneasy. What is reasonable?', ['Decline and stay in public', 'Go so you do not seem rude', 'Wait to see if danger is certain'], 0, 'You can decline before danger is certain.'), {practice:'Rehearse a simple sentence: “No, I am staying here.”'}),
    lesson('foundations.boundary', 'Say no clearly', 'Short boundaries are easier to use under stress than long explanations.', ['Face the direction of your exit.', 'Use a steady, audible sentence: “No. Please step back.”', 'Move away and seek support if the boundary is ignored.'], C('Someone keeps stepping closer after you ask for space. What next?', ['Repeat a long explanation', 'Create distance and seek help', 'Stand still to be polite'], 1, 'An ignored boundary is a cue to leave and involve others.'), {practice:'Say “Please give me space” aloud three times at a comfortable volume.'}),
    lesson('foundations.planning', 'A small safety plan', 'Make a plan you can remember: safer route, meeting point, contacts, and what to do if plans change.', ['Choose a familiar staffed place as a fallback.', 'Tell someone where you are going when appropriate.', 'If the route feels unsafe, change course toward help.'], C('Your usual route is unexpectedly closed and poorly lit. What is safer?', ['Take the unknown shortcut', 'Choose a known public route or ask for help', 'Keep walking without checking'], 1, 'Known, public routes reduce uncertainty.'), {practice:'Make a 20-second plan for one regular journey.'})
  ]},
  { id: 'awareness', title: 'See the whole picture', subtitle: 'Spot options without living on high alert.', icon: '◎', lessons: [
    lesson('awareness.scan', 'The gentle scan', 'Awareness is an occasional glance at people, exits, and changes—not constant fear.', ['When entering, notice exits and staffed areas.', 'Check whether your path is clear.', 'Return attention to what you were doing.'], C('You enter an unfamiliar café. Which habit helps most?', ['Stare at everyone', 'Notice exits and staff once', 'Sit where the door is hidden'], 1, 'A brief scan gives useful options without constant vigilance.'), {diagram:{heading:'A simple scan',labels:['Entry','People','Exit']}}),
    lesson('awareness.position', 'Choose an open position', 'Keep enough room to move toward a safer place. Avoid letting furniture or crowds trap your only exit.', ['Notice narrow corners and blocked doors.', 'Choose a position with a clear path.', 'Move early if your route closes.'], C('A group makes the only corridor feel crowded. What is useful?', ['Wait in the corner', 'Move toward an open staffed area', 'Push through the group'], 1, 'A clear route and support are better than forcing passage.'), {practice:'In one room, identify where you could move without crossing an obstacle.'}),
    lesson('awareness.route', 'Choose a safer route', 'A familiar, visible, populated route is often preferable to an isolated shortcut.', ['Compare lighting and people nearby.', 'Keep your phone usable but your eyes up.', 'Change route toward a public place if needed.'], C('Two paths are equally short. One is lit and busy, one isolated. Which is wiser?', ['The isolated route', 'The lit and busy route', 'Either without looking'], 1, 'Visibility and nearby help improve your options.'), {practice:'Compare two routes you know and name one safer feature of each.'}),
    lesson('awareness.followed', 'If you think you are followed', 'Do not head to a private destination to test the situation. Move toward staffed public help.', ['Stay in a public, well-lit area.', 'Change direction toward a staffed place; do not go home.', 'Call a trusted person or local emergency help if threatened.'], C('The same person follows several turns behind you. What is safest?', ['Go straight home', 'Enter a staffed public place and ask for help', 'Confront them alone'], 1, 'Staff and other people can help; home reveals a private location.'), {practice:'Name a staffed place along a route you use.'}),
    lesson('awareness.transport', 'Arrivals and departures', 'Transitions around transport can be distracting. Prepare your next step before you exit.', ['Check the stop and route while still in a safe area.', 'Keep belongings easy to carry.', 'Move toward a staffed or populated area if unsure.'], C('You arrive at an unfamiliar stop after dark. What helps?', ['Wander while looking at your phone', 'Pause in a visible area and check your route', 'Follow the nearest stranger'], 1, 'A short route check in a visible place is safer than wandering.'), {practice:'Mentally rehearse leaving a bus or train and finding the next safe landmark.'})
  ]},
  { id: 'voice', title: 'Words that make space', subtitle: 'Boundaries, de-escalation, and help seeking.', icon: '❝', lessons: [
    lesson('voice.boundaries', 'One-sentence boundaries', 'Use plain words, a steady tone, and a move toward your exit.', ['Say what you need: “Step back.”', 'Do not argue about your boundary.', 'Leave if it is ignored.'], C('Which boundary is easiest to use under pressure?', ['I am sorry but maybe...', 'Please step back', 'You always do this because...'], 1, 'Short words are easier to say and understand.'), {practice:'Practice “I need space” while stepping back one comfortable step.'}),
    lesson('voice.deescalate', 'Lower the temperature', 'When safe to do so, keep your voice calm and avoid insults or challenges while you move away.', ['Keep sentences short.', 'Avoid threats or proving a point.', 'Leave as soon as a route is available.'], C('A stranger argues about a minor bump. Which reply supports leaving?', ['“You are wrong!”', '“I do not want trouble. I am leaving.”', 'A long debate'], 1, 'A brief neutral response can reduce friction while you exit.'), {practice:'Say a neutral exit line in your own words.'}),
    lesson('voice.callhelp', 'Ask for specific help', 'A specific request makes it easier for bystanders to act.', ['Move toward people.', 'Address one person or staff member directly.', 'Say what you need: “Please call for help.”'], C('You need help in a busy shop. Which request is strongest?', ['Hope someone notices', '“You in the blue shirt, please call staff”', 'Whisper to no one'], 1, 'A direct request identifies a helper and an action.'), {practice:'Rehearse naming a helper and a concrete action.'}),
    lesson('voice.online', 'Pressure that begins online', 'A request to meet privately, share location, or keep a risky secret deserves a pause and trusted input.', ['Do not share live location with someone you do not trust.', 'Keep evidence of concerning messages.', 'Tell a trusted adult or person; block/report when appropriate.'], C('An online contact urges a secret private meeting. What is safer?', ['Go alone', 'Pause and tell a trusted person', 'Share your home address first'], 1, 'A trusted person can help you assess pressure and plan safely.'), {practice:'Review who can see your live location in one app you use.'}),
    lesson('voice.after', 'After an unsafe moment', 'Once safe, get medical, emotional, or official support as needed. There is no single “correct” reaction.', ['Reach a safe place.', 'Contact someone you trust or emergency services if needed.', 'Write down useful details only when safe and ready.'], C('You escaped a frightening situation. What is a sensible next step?', ['Handle everything alone', 'Get to safety and contact support', 'Return to argue'], 1, 'Support matters after the immediate danger ends.'), {practice:'Name one trusted person you could contact after a difficult event.'})
  ]},
  { id: 'movement', title: 'Move with room to leave', subtitle: 'Balance, distance, and a clear path.', icon: '↗', lessons: [
    lesson('movement.ready', 'A balanced ready stance', 'Stand comfortably with feet apart, knees soft, and weight centered so you can move in any direction.', ['Place feet about hip-width apart, one foot slightly back if comfortable.', 'Keep knees soft and shoulders relaxed.', 'Keep hands naturally available and eyes on an exit.'], C('What makes a ready stance useful?', ['Locked knees and narrow feet', 'Soft knees and balanced weight', 'Leaning far forward'], 1, 'Balance makes changing direction easier.'), {mode:'movement',assessmentId:'ready_stance',practice:'In clear space, hold a relaxed stance for three breaths. Stop if uncomfortable.',detail:'There is no perfect stance for every body. The goal is comfort, stability, and freedom to leave.',demo:[{label:'Start',text:'Stand naturally, looking toward your imagined exit.',pose:'neutral'},{label:'Set',text:'Place one foot a comfortable step to the side.',pose:'ready'},{label:'Finish',text:'Soften your knees and keep your head over your feet.',pose:'ready'}],cues:{do:'Keep your shoulders loose and room to move in either direction.',avoid:'Do not lock your knees or stretch so wide that you cannot step.'}}),
    lesson('movement.distance', 'Protect your personal space', 'Distance creates time to decide. Move early when someone enters a space that feels unsafe.', ['Notice whether you can step away.', 'Keep an open hand in front of you if you need a boundary.', 'Move toward your exit rather than standing your ground.'], C('Someone keeps closing distance. Which response supports safety?', ['Wait until contact', 'Step away and set a verbal boundary', 'Move toward them'], 1, 'Early movement gives you more options.'), {mode:'movement',practice:'With no partner, mark a comfortable personal-space circle and step out toward an exit.'}),
    lesson('movement.stepback', 'Step back without losing balance', 'A controlled step back can create room while keeping you ready to turn and leave.', ['Look toward a clear path.', 'Move the rear foot first, then bring the other foot to a stable width.', 'Keep your head over your base; do not cross your feet.'], C('What should you avoid during a step back?', ['Keeping balance', 'Crossing your feet', 'Looking for an exit'], 1, 'Crossed feet can make it harder to move again.'), {mode:'movement',practice:'In clear space, take two slow steps back and return. No speed goal.'}),
    lesson('movement.angle', 'Turn toward an exit', 'An angle can open a route around an obstacle. Keep your feet under you and move toward safety.', ['Locate the open route.', 'Turn your body and take one controlled side step.', 'Continue away; do not circle back toward danger.'], C('What is the purpose of angling away?', ['To win a contest', 'To open a path to leave', 'To stay close'], 1, 'The angle creates a route to safety.'), {mode:'movement',assessmentId:'side_step',practice:'Place a soft object on the floor as an obstacle. Step around it slowly toward an imaginary exit.',demo:[{label:'Start',text:'Find the open side and begin from a balanced stance.',pose:'ready'},{label:'Move',text:'Step one foot toward the opening, keeping your head level.',pose:'step'},{label:'Settle',text:'Bring the other foot under you. Keep moving toward safety.',pose:'ready'}],cues:{do:'Keep some space between your feet as you move.',avoid:'Do not cross your feet or step toward the obstacle.'}}),
    lesson('movement.run', 'Know when to run', 'If a safe path opens and you can leave, going to people and help is often the best choice.', ['Choose the clearest route.', 'Leave possessions if they slow a safe escape.', 'Once away, seek help and do not return alone.'], C('An open exit appears during a threatening encounter. What is the priority?', ['Stay to finish talking', 'Leave and get help', 'Collect every item first'], 1, 'Distance and help matter more than belongings.'), {practice:'Picture one place where you could run to staffed help.'})
  ]},
  { id: 'position', title: 'Protect and recover', subtitle: 'Simple solo body positioning.', icon: '◇', lessons: [
    lesson('position.guard', 'An open-hand guard', 'Raise open hands near your upper chest and face without looking confrontational. This can protect space while you speak and move.', ['Bring hands to a comfortable height below your eyes.', 'Keep elbows relaxed and near your ribs.', 'Keep shoulders down and look toward an exit.'], C('Which guard is more useful for leaving?', ['Hands low and elbows locked', 'Open hands, soft elbows, clear vision', 'Eyes closed'], 1, 'Open hands and clear vision support movement and communication.'), {mode:'movement',assessmentId:'open_guard',practice:'In clear space, say “Please step back” while gently raising open hands.',demo:[{label:'Start',text:'Stand balanced with relaxed arms.',pose:'ready'},{label:'Lift',text:'Bring open hands up toward your upper chest.',pose:'guard'},{label:'Finish',text:'Keep elbows soft and your eyes on the exit.',pose:'guard'}],cues:{do:'Show open palms and keep your shoulders low.',avoid:'Do not cover your own eyes or straighten your elbows rigidly.'}}),
    lesson('position.head', 'Protect your head', 'If you cannot immediately leave, bring forearms near the sides of your head, chin gently down, and keep moving toward safety.', ['Cover the sides of your head without blocking all vision.', 'Keep elbows forward rather than flaring wide.', 'Move toward an exit; call for help.'], C('What should you preserve while protecting your head?', ['A view of your exit', 'A rigid posture', 'A reason to stay'], 0, 'You still need to see and move toward safety.'), {mode:'movement',assessmentId:'head_cover',practice:'Slowly form the cover for one breath and release. Avoid pressure on your neck.',demo:[{label:'Start',text:'Begin in a balanced position with eyes open.',pose:'ready'},{label:'Cover',text:'Bring your hands beside your head, not over your eyes.',pose:'cover'},{label:'Leave',text:'Look toward your exit while maintaining the cover.',pose:'cover'}],cues:{do:'Keep the sides of your head protected and your view clear.',avoid:'Do not twist your neck or squeeze your head with your hands.'}}),
    lesson('position.fall', 'If you fall', 'Protect your head, avoid rushing upright into someone, and look for a clear route before standing.', ['Curl slightly and protect your head.', 'Create space with your feet if needed without aiming to injure.', 'Look for a safe opening to rise and leave.'], C('After a fall, what comes before standing?', ['Checking space and protecting your head', 'Closing your eyes', 'Reaching blindly'], 0, 'A quick scan can prevent moving into danger.'), {mode:'movement',practice:'On a soft mat with clear space, rehearse a slow, comfortable recovery. Skip if this is unsafe for you.'}),
    lesson('position.rise', 'Return to your feet', 'Practice a controlled rise from the floor while keeping your view toward a safe exit.', ['Sit or kneel in a comfortable position.', 'Use one hand for support while the other stays available.', 'Stand without rushing, then move away.'], C('Why rise in a controlled way?', ['To keep balance and see your route', 'To look impressive', 'To stay on the floor longer'], 0, 'Balance and awareness help you leave safely.'), {mode:'movement',practice:'Use a stable surface if needed. Practice slowly and stop with pain.'}),
    lesson('position.breath', 'Reset under pressure', 'One breath and a simple plan can help interrupt freezing: see exit, move, ask for help.', ['Exhale once and look around.', 'Name the closest safer place.', 'Take one concrete action.'], C('You freeze for a moment. What is a useful first action?', ['Judge yourself', 'Exhale and find one exit', 'Wait for a perfect plan'], 1, 'A small action can restart decision-making.'), {practice:'Exhale slowly, point to an exit, and say a simple next action.'})
  ]},
  { id: 'contact', title: 'Break contact, then leave', subtitle: 'Understand limits; practice safely and solo first.', icon: '↖', lessons: [
    lesson('contact.grip', 'When a wrist is held', 'A grip release is uncertain. Prioritize voice, movement, and escape. Never practice forcefully or with an unwilling partner.', ['Keep your balance and look for a way out.', 'Turn your wrist toward the opening near the holder’s thumb while stepping away.', 'Leave immediately; ask for help.'], C('After a grip loosens, what is the priority?', ['Stay to demonstrate the move', 'Move away and get help', 'Try to control the other person'], 1, 'A release is only useful if it creates an exit.'), {mode:'partner',practice:'Solo: use your own opposite hand with very light contact to feel where your thumb opens. Stop if it hurts.',detail:'This idea may not work against a stronger grip or changing situation. A partner drill requires consent, gentle pressure, and supervision.'}),
    lesson('contact.clothing', 'Clothing is grabbed', 'Do not rely on a single move. Protect balance, use your voice, and move toward help.', ['Keep feet under you and avoid yanking backward.', 'Use clear words and seek a gap.', 'Leave belongings if doing so creates a safe exit.'], C('Someone grabs a jacket strap. What can matter more than the jacket?', ['Keeping the jacket', 'Your route to safety', 'Winning the argument'], 1, 'Items can be replaced; your escape route matters.'), {mode:'partner',practice:'Solo: imagine setting down a bag and moving to a clear doorway. No force needed.'}),
    lesson('contact.space', 'Create space without chasing', 'A protective frame with open forearms can help maintain distance while you move away. Do not advance to strike.', ['Keep hands open and elbows soft.', 'Orient toward your route.', 'Move away as soon as you have room.'], C('What is the purpose of a protective frame?', ['Create room to leave', 'Push someone down', 'Keep the encounter going'], 0, 'The frame serves the exit, not a confrontation.'), {mode:'movement',practice:'Solo: hold open palms in front of your chest and take one step toward an exit.'}),
    lesson('contact.limits', 'Know the limits of drills', 'A camera sees only one body. It cannot judge another person’s intent, a grip, or whether a release will work.', ['Practice solo movement and decisions first.', 'For partner practice, ask consent and keep pressure light.', 'Never treat a camera score as proof of safety.'], C('Can a solo pose score confirm that a two-person release is effective?', ['Yes, always', 'No', 'Only after many attempts'], 1, 'A single-person pose cannot measure a partner’s grip or response.'), {practice:'Explain to yourself what the camera can and cannot measure.'}),
    lesson('contact.after', 'Leave after contact', 'Once you break away, create distance and seek support. Do not return to retrieve an item alone.', ['Move to people or a staffed place.', 'Call for help if needed.', 'Seek medical attention for injury.'], C('You reach a safe shop after contact. What next?', ['Return alone for your bag', 'Ask staff for help', 'Keep the incident secret'], 1, 'Staff can help you contact support safely.'), {practice:'Name a safe place you could reach on a familiar route.'})
  ]},
  { id: 'scenarios', title: 'Choose under pressure', subtitle: 'Use your options in realistic situations.', icon: '◌', lessons: [
    lesson('scenarios.street', 'Someone asks you to move', 'A stranger asks you to step behind a building to show you something. You can decline without explaining.', ['Stay in the public area.', 'Say “No, I am staying here.”', 'Move toward others if pressured.'], C('They keep insisting. What is safest?', ['Follow to avoid rudeness', 'Decline and move toward people', 'Argue about their reasons'], 1, 'Pressure is a reason to increase distance and find help.'), {practice:'Rehearse your own short refusal.'}),
    lesson('scenarios.party', 'A crowded gathering', 'Crowds can obscure exits. Keep track of your group and the nearest staffed or public area.', ['Notice exits on arrival.', 'Tell a trusted person if you leave.', 'If uncomfortable, move to staff or a safer group.'], C('Your friend has disappeared and you feel unsafe. What helps?', ['Wait alone in a secluded room', 'Find staff and contact your friend', 'Follow a stranger to look for them'], 1, 'Staff and a known contact provide support.'), {practice:'Imagine entering a crowded venue and locating two exits.'}),
    lesson('scenarios.transit', 'A quiet platform', 'When a platform feels unsafe, choose visibility and proximity to help.', ['Move near lighting, cameras, or staff if available.', 'Keep enough space to leave.', 'Call for help if you are threatened.'], C('Someone repeatedly approaches despite a boundary. What next?', ['Move near staff or others', 'Stay alone to avoid attention', 'Try to win the argument'], 0, 'Support and distance improve your options.'), {practice:'Name where staff or a help point may be found on your usual route.'}),
    lesson('scenarios.school', 'A school corridor', 'If another student pressures or threatens you, prioritize leaving and getting an adult’s help.', ['Move toward a supervised area.', 'Use a short boundary if safe.', 'Tell a trusted adult what happened.'], C('A student corners you after class. What is a safe aim?', ['Prove you can fight', 'Reach a supervised area', 'Keep it secret'], 1, 'A supervised area provides immediate support.'), {practice:'Name two adults or staffed places available at school or work.'}),
    lesson('scenarios.home', 'A plan changes', 'When a ride or route changes unexpectedly, communicate and choose a safe waiting place.', ['Stay in a visible public area.', 'Contact a trusted person.', 'Use a verified alternative ride or route.'], C('Your ride cancels and your phone battery is low. What first?', ['Walk into an unknown area', 'Find staff and contact a trusted person', 'Accept an unverified ride'], 1, 'Staff and a trusted contact help you plan a safer next step.'), {practice:'Think through one backup for a regular trip.'})
  ]},
  { id: 'review', title: 'Make it yours', subtitle: 'Build a repeatable safety routine.', icon: '✦', lessons: [
    lesson('review.checkin', 'Your two-minute check-in', 'A regular brief check-in builds habits without constant worry.', ['Notice your route and exits.', 'Check who you can contact.', 'Choose one small improvement for today.'], C('What is a useful daily check-in?', ['Constant scanning', 'A brief route and support review', 'Avoiding all places'], 1, 'A short practical review supports readiness.'), {practice:'Try a two-minute route and contact check today.'}),
    lesson('review.mix', 'Combine voice and movement', 'Words and movement work together: set a boundary, step away, and seek help.', ['Say a short boundary.', 'Move toward an exit with balanced feet.', 'Address a helper directly.'], C('Someone ignores “step back.” What next?', ['Stay and repeat forever', 'Move away and ask for help', 'Move closer'], 1, 'Boundary, distance, and support work together.'), {mode:'movement',practice:'In clear space, rehearse the three actions slowly.'}),
    lesson('review.plan', 'Build your personal plan', 'Your best plan fits your real routes, needs, and support network.', ['Name a safer route and fallback place.', 'Name two trusted contacts.', 'Know how to request emergency help locally.'], C('What makes a safety plan useful?', ['A long script you cannot recall', 'Simple actions for places you actually use', 'One move for every situation'], 1, 'A practical plan is specific and memorable.'), {practice:'Write a three-line plan in a private note if useful.'}),
    lesson('review.uncertainty', 'Stay flexible', 'No checklist predicts every situation. Change plans when the environment changes.', ['Notice when an option becomes unsafe.', 'Choose a different route or helper.', 'Put safety ahead of completing the original plan.'], C('Your planned exit is blocked. What now?', ['Keep trying the same path', 'Look for another exit or staffed help', 'Stop thinking'], 1, 'Flexible choices matter more than perfect scripts.'), {practice:'Imagine one blocked exit and name two alternatives.'}),
    lesson('review.next', 'Keep learning safely', 'Repeat what helps, practice gently, and get in-person instruction from qualified teachers when possible.', ['Review weak quiz topics.', 'Revisit camera feedback without chasing a perfect score.', 'Keep practicing awareness, boundaries, and help seeking.'], C('What is a healthy goal for practice?', ['Perfect camera scores', 'Safer decisions and controlled movement', 'Risky speed'], 1, 'Learning is about usable habits, not performance for a score.'), {practice:'Choose one skill to revisit this week.'})
  ]}
];
export const lessons = units.flatMap(unit => unit.lessons.map((item, index) => ({ ...item, unitId: unit.id, order: index })));
export const lessonById = new Map(lessons.map(item => [item.id, item]));
export const unitById = new Map(units.map(item => [item.id, item]));
